### ISSUE TITLE
Slate editor doesn't display field title

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/form-builder#13]
See slate fields in schema here: https://github.com/sanity-io/form-builder/blob/4b463a6d1c5b45a2e94708bd24ac9b01d8285f96/examples/schema-testbed/schemas/blocks.js

This is how its rendered:
![image](https://cloud.githubusercontent.com/assets/876086/19888023/55dc00a0-a02c-11e6-8a22-3d51ec061308.png)

**Comment by skogsmaskin** [comment]
Fixed in 494f49006ad477e184855210377b2392808b040e
